### ISSUE TITLE
Merging back EcoTaxa samples into their original project looses the connection with EcoPart samples

### ISSUE THREAD

**Issue by rkiko** [oceanomics/ecotaxa_dev#404] opened 2020-05-15 12:02 UTC
I created a subset from project 622 containing some samples I wanted to sort, 

I deleted the respective samples in 622 (actually, the samples were not „deleted", only the images. The sample id is still listed on ecotaxa)

I merged the subset with another subset, sorted the stuff.

I then separated the subsets again, and merged the resulting secondary subsets with the original project.

This procedure created the following issues (see attached excel):

In samples (and maybe other places) the projid of the profiles from the subsample is now  970 instead of 622.

What is even worse is that the sampleid was changed. As far as I get it, the ecopart sampleid and the ecotaxa sampleid need to be identical in order to create aggregated data in ecopart.

That the sampleid changed is also bad with respect to the fact that the same image could also belong to two samples. That is physically not possible. I understand that this is due to the fact that the sampleid is a primary key in samples, but then the sample should just not be duplicated when creating a subset. There should be a different solution… 

Please disable the option to create subsets. There are too many bugs in this function to allow its use.

[sub_samples.xlsx](https://github.com/oceanomics/ecotaxa_dev/files/4634218/sub_samples.xlsx)

**Comment by jiho** [comment] 2020-05-15 16:58
The problem is that the samples get a new internal id when they are merged back into 622; the link from the EcoPart sample to the EcoTaxa sample is therefore lost

Example
```
  projid title                 sampleid taxaProfileName pprojid ptitle psampleid partProfileName     n
1    622 UVP5 Geomar 2017 m138    47037 c_m138_003           98 M 138      16870 c_m138_003        589
2    622 UVP5 Geomar 2017 m138    47017 c_m138_086           98 M 138      16898 c_m138_086         0
3    622 UVP5 Geomar 2017 m138   126584 c_m138_086           98 M 138         NA NA                967
```

`c_m138_003` is a profile that stayed in the project and the `psampleid` (EcoPart) and `sampleid` are matched.
`c_m138_086` that was moved around. It appears twice, once as sample `47017` which is correctly linked with EcoPart but is actually empty (`0` objects) and once as sample `126584` which had data but is not linked to EcoPart.

**Comment by jiho** [comment] 2020-05-15 17:02
The immediate solution is to relink samples. This happens automatically every night and can be forced from EcoPart's interface (@picheral : where is it?)

The long term solution is #405

**Comment by grololo06** [comment] 2020-05-15 17:13
I reopen before forgetting because, apart from the issue seen, it's linked to other topics currently of interest:
- Unicity of images
- Nature of the links b/w EcoPart and EcoTaxa
- Subsett-ing usefulness in its current form
- Merge control

**Comment by picheral** [comment] 2020-05-15 17:21
![image](https://user-images.githubusercontent.com/18468240/82078375-553b9e80-96e1-11ea-8299-05c45223c0d0.png)

**Comment by rkiko** [comment] 2020-05-15 17:29
Do I need to type in the sampleID from ecotaxa into the ID field to match it, then cross Match ecotaxa sample, then hit start operation?

**Comment by jiho** [comment] 2020-05-15 20:56
@rkiko no, it is automatic, based on the original zooprocess profile id. My only worry is what happens when this id is associated to two samples in EcoTaxa. You may want to wait tomorrow morning for these samples to be removed.

**Comment by jiho** [comment] 2020-05-15 21:03
@grololo06 

>     * Unicity of images

Objects in a subset become conceptually separate from their origin. This is used often: a subset of data may be taken for demonstration purposes and images would get a new name in the new project that is not appropriate to propagate to the old one, some may be deleted or renamed together with others to build a specific training set, etc.

The strict hierarchy project > sample > ... > object is simple to grasp conceptually. If an object can belong to several projects, it becomes messy.

>     * Subsett-ing usefulness in its current form

Subsetting is fine, merging is the problem.

>     * Merge control

My impression is that, the main problem here, is that the same information is stored in two places and therefore has to be linked. This should not have happened. The decision to duplicate all UVP samples in `part_samples` made some things easier but was a bad, IMHO, design decision from a database point of view. It needs to be reverted.

The use case of Rainer here is:
- extract subsets from several projects
- merge them
- sort them homogeneously
- re-merge each original subset in its original project.
This use case would be better served by #335 .

**Comment by grololo06** [comment] 2020-05-16 05:21
@jiho there is probably a question about EcoTaxa "mission statement". To me, the 'core business' is:
- storing e.g. "At time XXXX, coordinates YYYY, depth D, there was this image", 
- determining "this image is a Copepod"
...which is already very hard. 

The other use cases of data should be tagged as such, implementing e.g. #387. For now I see naming conventions in duplicated data, projects named "demo xxx" or "model yyy" or "learning zzz", but no formal storage of "this is a clone" information. All this, not talking about technical aspects like  disk space.

https://en.wikipedia.org/wiki/Single_source_of_truth

**Comment by rkiko** [comment] 2020-05-17 16:49
Hi,
I like the single source of truth aspect. I think that project, sample and depth info needs to be unique and should not be copied. This could be done by branching or using links/views instead of creating copies when generating a subset. The sample and project info should be sacred. We could start using checksums to identify each image (or define a unique identifier in a different way) and only this info is forwarded to a branch/subset. All other info should stay in the original project as should the original image. 

The only thing that is flexible (as it depends on user opinion) is the classification. This can be changed in subsets/branches and could be merged back to the original project.

Hmm, I guess I just wrote what Laurent wrote in more words ...


"""JO wrote: The strict hierarchy project > sample > ... > object is simple to grasp conceptually. If an object can belong to several projects, it becomes messy.""" But it is messy right now. Maybe not at the surface, but under the hood, which is even worse... Marking as master and branch/clone could be the better solution ...

**Comment by grololo06** [comment] 2020-09-24 13:33
Another occurence today.

**Comment by rkiko** [comment] 2020-09-24 13:42
The link between ecopart and ecotaxa can also not be forced, as two profiles with the same info still exist. The images of the original profile are deleted, but the profile metadata still exists. There is a "ghost profile" in the project.

**Comment by rkiko** [comment] 2020-09-24 13:45
OK, Laurent deleted the "Ghost profile" by launching the overnight job.

**Comment by rkiko** [comment] 2020-09-24 15:42
Found out that ghost profiles are only automatically deleted, if they are not linked in ecopart...

**Comment by grololo06** [comment] 2020-12-09 08:32
Believe it or not, starting with 2.5.0, merging back into the original project will keep the original (numerical) sampleid, as the match is done using the (now unique) sample orig_id. #546 is partially solved (i.e. for all but not objects).

**Closed by grololo06** 2020-12-09 08:32 UTC
Labels: bug, page_merge, page_subset
